---
abstract: 'brand new module Acme::Foo'
author:
  - 'alexbyk <alex@alexbyk.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Foo
resources:
  bugtracker: http://github.com/alexbyk/Acme-Foo/issues
  repository: http://github.com/alexbyk/Acme-Foo
version: 0.00_10
